### ISSUE TITLE
Timezone set

### ISSUE THREAD

**Issue by KeJyLL** [tchapi/davis#132]
First of all, thanks for your great work!

I just tried to update my container with the new enviroment options "APP_TIMEZONE", but it seems doesn't working. 

```
davis:
    image: ghcr.io/tchapi/davis:v4.4.1
    container_name: davis
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=sqlite
      - DATABASE_URL=sqlite:////data/davis-database.db # ⚠️ 4 slashes for an absolute path ⚠️ + no quotes (so Symfony can resolve it)
      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_REALM=${AUTH_REALM}
      - AUTH_METHOD=${AUTH_METHOD}
      - CALDAV_ENABLED=${CALDAV_ENABLED}
      - CARDDAV_ENABLED=${CARDDAV_ENABLED}
      - WEBDAV_ENABLED=${WEBDAV_ENABLED}
      - WEBDAV_TMP_DIR=${WEBDAV_TMP_DIR}
      - WEBDAV_PUBLIC_DIR=${WEBDAV_PUBLIC_DIR}
      - INVITE_FROM_ADDRESS=${INVITE_FROM_ADDRESS}
#      - WEBDAV_PUBLIC_DIR=/webdav
      - APP_TIMEZONE="Europe/Berlin"
    volumes:
      - davis_www:/var/www/davis
      - davis_data:/data
    restart: always
```
I also tried the other way with the .env (I haven't forget to set back the enviroment from earlier to 
`- APP_TIMEZONE=${TIMEZONE}`
Furthermore I tried to cause an error with this line:
`TIMEZONE=Europasde/Paris`

On the webGUI, I get everytime this:
![grafik](https://github.com/tchapi/davis/assets/140980814/1e1eab78-0f0d-4334-941c-ac5da9ab4740)

I also checked the following file (it's empty):
`/usr/local/etc/php/conf.d/timezone.ini`
