### ISSUE TITLE
Unable to login using a Docker image

### ISSUE THREAD

**Issue by kang-makes** [tchapi/davis#149]
I had to do an ugly hack to make this software works on Docker/Kubernetes because the reverse proxy was unable to find the files.

These are configurations:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: davis
data:
  APP_ENV: "prod"
  APP_TIMEZONE: "Europe/Madrid"
  CALDAV_ENABLED: "true"
  CARDDAV_ENABLED: "true"
  WEBDAV_ENABLED: "false"

  DATABASE_DRIVER: "postgresql"

  AUTH_REALM: SabreDAV
  AUTH_METHOD: Basic

  DATABASE_URL: "postgres://davis:<REDACTED>@postgres:5432/davis?serverVersion=15&charset=UTF-8"

  ADMIN_LOGIN: "admin"
  ADMIN_PASSWORD: "<REDACTED>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    worker_processes auto;
    error_log stderr warn;

    events {
      worker_connections  512;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      keepalive_timeout 30;

      upstream davis-sidecar {
        server localhost:9000;
      }

      server {
        server_name _;
        listen 80;
        access_log off;

        root /var/www/davis/public/;
        index index.php;

        rewrite ^/.well-known/caldav /dav/ redirect;
        rewrite ^/.well-known/carddav /dav/ redirect;

        charset utf-8;

        location ~ /(\.ht) {
          deny all;
          return 404;
        }

        location /health {
          add_header Content-Type text/plain;
          return 200 'ALIVE';
        }

        location / {
          try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
          fastcgi_pass    davis-sidecar;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;

          fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;
          fastcgi_param   PATH_INFO        $fastcgi_path_info;
          fastcgi_split_path_info  ^(.+\.php)(.*)$;
        }

        location ~ \.php$ {
          return 404;
        }
      }
    }
``` 

Then, this is a snippet of the manifest I am using to deploy it.

```yaml
      initContainers:
      - name: migration-runner
        image: ghcr.io/tchapi/davis:v4.4.1
        command:
          - /var/www/davis/bin/console
          - doctrine:migrations:migrate
          - --no-interaction
        envFrom:
          - configMapRef:
              name: davis
      - name: public-populator
        image: ghcr.io/tchapi/davis:v4.4.1
        command:
          - ash
          - -c
          - find /var/www/davis/public -maxdepth 1 -exec cp -rv {} /new-public \;
        volumeMounts:
          - mountPath: /new-public
            name: public
      containers:
      - name: davis
        image: ghcr.io/tchapi/davis:v4.4.1
        envFrom:
          - configMapRef:
              name: davis
        volumeMounts:
          - mountPath: /var/www/davis/var/log
            name: logs
          - mountPath: /var/www/davis/public
            name: public
      - name: nginx
        image: nginx:1.25-bookworm
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: config
            subPath: nginx.conf
          - mountPath: /var/www/davis/public
            name: public
      volumes:
        - name: config
          configMap:
            name: nginx
        - name: logs
          emptyDir: {}
        - name: public
          emptyDir: {}
```

In case you are not familiar with Kuberentes, I can explain you:

At `volumes` I specify a couple of empy volumes where I am going to save the files at `public` and logs and I get use one of the configMaps as a file for nginx.

The other configMap is uses as key-value and mapped as environment variables using this:
```
