### ISSUE TITLE
Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle". when run in docker

### ISSUE THREAD

**Issue by Lxtharia** [tchapi/davis#151]
built the docker and ran it with this docker-compose file

```yaml
version: "3.7"
name: "davis-docker"

services:

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - davis
    volumes:
      - davis_www:/var/www/davis
      - type: bind
        source: ./configurations/davis.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 5050:80

  davis:
    build:
      context: ./repo/
      dockerfile: ./docker/Dockerfile
      args:
        fpm_user: 101:101
    image: davis:latest
    # If you want to use a prebuilt image from Github
    # image: ghcr.io/tchapi/davis:edge
    container_name: davis
    env_file: 
      - path: .env.local
    volumes:
      - davis_www:/var/www/davis
      - davis_data:/data

volumes:
  davis_www:
    name: davis_www
  davis_data:
    name: davis_data
```
and the `.env.local`:
```env
# For the MariaDB container mainly
DB_ROOT_PASSWORD=notSoSecure

TIMEZONE=Europe/Berlin

# The Davis database, user and password
DB_DATABASE=davis
DB_USER=davis_user
DB_PASSWORD=davis_password

# For the Davis app
ADMIN_LOGIN=admin
ADMIN_PASSWORD=test

AUTH_REALM=SabreDAV
# Auth Method for the frontend
# "Basic", "IMAP", or "LDAP"
AUTH_METHOD=LDAP

# In case of LDAP Auth, you must specify the url of the LDAP server
# See https://www.php.net/manual/en/function.ldap-connect for more details
LDAP_AUTH_URL="ldap://127.0.0.1:389"
LDAP_DN_PATTERN="uid=%u"
LDAP_MAIL_ATTRIBUTE="mail"
LDAP_AUTH_USER_AUTOCREATE=false

CALDAV_ENABLED=true
CARDDAV_ENABLED=true
WEBDAV_ENABLED=false

WEBDAV_TMP_DIR='/tmp'
WEBDAV_PUBLIC_DIR='/webdav'

# INVITE_FROM_ADDRESS=no-reply@example.org
# MAIL_HOST=smtp.myprovider.com
# MAIL_PORT=587
# MAIL_USERNAME=userdav
# MAIL_PASSWORD=test
                                                                                                                                                                                                                                            
```

On the webinterface i get this error page:
![06-032024_192458  firefox](https://github.com/tchapi/davis/assets/87075045/366d1ac5-85fc-4cac-bd93-486cc3b82c04)

Thanks in advance!
