### ISSUE TITLE
500 error upon login with `docker-compose-standalone`

### ISSUE THREAD

**Issue by RCdeWit** [tchapi/davis#159]
I am trying to get Davis to run on my Synology NAS. I use Portainer to manage my Docker stacks.

I have a reverse proxy hosted elsewhere that connects to my NAS over Tailscale, so I think I need to use the standalone version.

I have adapted the `docker-compose-standalone` to the following:

```
version: "3.7"
name: "davis"

services:

  mysql:
    image: mariadb:10.6.10
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /volume1/docker/davis/database:/var/lib/mysql

  davis:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-standalone
    # image: davis:latest
    # If you want to use a prebuilt image from Github
    image: ghcr.io/tchapi/davis-standalone:edge
    container_name: davis-standalone
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=mysql
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}?serverVersion=mariadb-10.6.10&charset=utf8mb4
      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_REALM=${AUTH_REALM}
      - AUTH_METHOD=${AUTH_METHOD}
      - CALDAV_ENABLED=${CALDAV_ENABLED}
      - CARDDAV_ENABLED=${CARDDAV_ENABLED}
      - WEBDAV_ENABLED=${WEBDAV_ENABLED}
      - WEBDAV_TMP_DIR=${WEBDAV_TMP_DIR}
      - WEBDAV_PUBLIC_DIR=${WEBDAV_PUBLIC_DIR}
      - INVITE_FROM_ADDRESS=${INVITE_FROM_ADDRESS}
      - APP_TIMEZONE=${TIMEZONE}
    depends_on:
      - mysql
    ports:
      - 8444:9000

volumes:
  database:
    name: database
```

Basically, I have changed the port because Portainer uses `:9000` and the volume to match a directory on my NAS. I have also executed `bin/console doctrine:migrations:migrate` through the console of the `docker-standalone` container, although I can't see whether it succeeded.

I can access `:8444/dashboard` and get a login page. Whenever I try to log in with the `ADMIN_LOGIN`/`ADMIN_PASSWORD` credentials, I am redirected to a 500 page.

The logs of the `davis-standalone` container don't show anything off, although Portainer does give it the `Unhealthy` label.

Any help would be much appreciated!
