### ISSUE TITLE
Volume bind mounts in docker not populating

### ISSUE THREAD

**Issue by be-side** [tchapi/davis#179]
Using the [docker-compose.yml](https://github.com/tchapi/davis/blob/main/docker/docker-compose.yml) in the repo as a base, I wanted to adapt it to use my existing reverse-proxy in a separate stack. Tried to mount the /var/www/davis folder as a bind mount to the host but when I start the container, it populates the folder but not the contents inside it.

The compose file used looks like this:
```
  davis:
    image: ghcr.io/tchapi/davis:latest
    container_name: davis
    environment:
      - ~~
    depends_on:
      - mysql
    volumes:
      - ./var/www/davis:/var/www/davis
```

I might be missing something here but in all other containers I have used previously, if the bind mount location on the host is empty, the container would usually create the folder and populate it.
