### ISSUE TITLE
401 under Traefik proxy

### ISSUE THREAD

**Issue by magiceupho** [tchapi/davis#182]
Hi,

Thank you for this app.

I have install Davis on my personal server with a Apache/PHP Docker container with Traefik as load balancer (redirect to https, LetsEncrypt certResolver).
The dashboard is working well.
But I can't connect to CalDAV with my MacOS BusyCal app: 401 error "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." 

Could you help me please ?

Regards,
magiceupho

**Comment by robflate** [comment]
Please can you provide your docker-compose?

**Comment by magiceupho** [comment]
Hi,

Here is the docker-compose for the apache-php container:
```yaml
services:
    apache-php:
        container_name: apache-php
        image: webdevops/php-apache:8.2-alpine
        networks:
            - web
            - utils-network
        restart: always
        environment:
            - PUID=1000
            - PGID=33
            - TZ=Europe/Paris
            - WEB_DOCUMENT_ROOT=/var/www/html
            - ENV=prod
        ports:
            - "80"
        labels:
            - traefik.enable=true
            - traefik.http.routers.lamp.entrypoints=web-secure
            - traefik.http.routers.lamp.tls=true
            - traefik.http.routers.lamp.tls.certresolver=LetsEncrypt
            - traefik.http.routers.lamp.tls.domains[0].main=exemple.fr
            - traefik.http.routers.lamp.tls.domains[0].sans=davis.exemple.fr
            - traefik.http.routers.lamp.rule=Host(`davis.exemple.fr`)
            - traefik.http.routers.lamp.priority=1
            - traefik.http.routers.lamp.middlewares=security-headers@docker
        volumes:
            - /docker/apache-php/www:/var/www/html
            - /docker/apache-php/config/php.ini:/opt/docker/etc/php/php.ini
            - /docker/apache-php/config/vhost.conf:/opt/docker/etc/httpd/vhost.conf
        external_links:
            - db

networks:
    web:
        external: true
    utils-network:
        external: true
```

And here for traefik container:
```yml
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
    command: --api
    networks:
      - web
      - utils-network
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.security-headers.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.security-headers.headers.stsPreload=true
      - traefik.http.middlewares.security-headers.headers.stsSeconds=31536000
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=security-headers@docker
      - traefik.http.routers.dashboard.entrypoints=web-secure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=LetsEncrypt
      - traefik.http.routers.dashboard.rule=Host(`traefik.exemple.fr`)
      - traefik.http.routers.dashboard.priority=10
    healthcheck:
      test: "/usr/bin/wget -q -T 15 -O /dev/null http://localhost/ping"
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./common.yml:/etc/traefik/common.yml:ro
      - ./acme.json:/acme.json
      - ./logs:/var/log/traefik

networks:
  web:
    external: true
  utils-network:
    external: true
```

Regards,
magiceupho
