### ISSUE TITLE
Can not make docker compose file to work

### ISSUE THREAD

**Issue by BaccanoMob** [tchapi/davis#191]
Steps I did:

1. `git clone https://github.com/tchapi/davis.git`
2. `cd davis/docker`
3. `docker compose up -d` and wait for build to finish (I also tried prebuilt images from github edge)
4. Open `<IP_ADDRESS>:9000/login`, and user/pass as admin/admin => Submit

![Image](https://github.com/user-attachments/assets/a35470ab-169e-42d2-9821-4d68de7e64de)

5. `docker compose down`
6. Change `prod` to `dev` and follow your [this comment](https://github.com/tchapi/davis/issues/158#issuecomment-2111112196)
7. `docker compose up -d` and wait for build to finish (I also tried prebuilt images from github edge)
8. Open `<IP_ADDRESS>:9000/login`

![Image](https://github.com/user-attachments/assets/fbbd24c1-b78e-4d39-8ffb-df0e928218e4)

Stack Trace:

```
UnexpectedValueException:
The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Matched route "app_login".
Context: {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http:\/\/100.84.174.23:9000\/login","method":"GET"}" at StreamHandler.php line 156
Context: {"exception":{}}" at StreamHandler.php line 156
Context: {"exception":{}}

  at /var/www/davis/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:156
  at Monolog\Handler\StreamHandler->write(object(LogRecord))
     (/var/www/davis/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:44)
  at Monolog\Handler\AbstractProcessingHandler->handle(object(LogRecord))
     (/var/www/davis/vendor/monolog/monolog/src/Monolog/Logger.php:391)
  at Monolog\Logger->addRecord(object(Level), 'Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission deniedThe exception occurred while attempting to log: Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission deniedThe exception occurred while attempting to log: Matched route "app_login".Context: {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\\\Controller\\\\SecurityController::login"},"request_uri":"http:\\/\\/100.84.174.23:9000\\/login","method":"GET"}" at StreamHandler.php line 156Context: {"exception":{}}" at StreamHandler.php line 156', array('exception' => object(UnexpectedValueException)))
     (/var/www/davis/vendor/monolog/monolog/src/Monolog/Logger.php:581)
  at Monolog\Logger->log(object(Level), 'Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission deniedThe exception occurred while attempting to log: Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission deniedThe exception occurred while attempting to log: Matched route "app_login".Context: {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\\\Controller\\\\SecurityController::login"},"request_uri":"http:\\/\\/100.84.174.23:9000\\/login","method":"GET"}" at StreamHandler.php line 156Context: {"exception":{}}" at StreamHandler.php line 156', array('exception' => object(UnexpectedValueException)))
     (/var/www/davis/vendor/symfony/http-kernel/EventListener/ErrorListener.php:171)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->logException(object(UnexpectedValueException), 'Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission deniedThe exception occurred while attempting to log: Uncaught PHP Exception UnexpectedValueException: "The stream or file "/var/www/davis/var/log/dev.log" could not be opened in append mode: Failed to open stream: Permission deniedThe exception occurred while attempting to log: Matched route "app_login".Context: {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\\\Controller\\\\SecurityController::login"},"request_uri":"http:\\/\\/100.84.174.23:9000\\/login","method":"GET"}" at StreamHandler.php line 156Context: {"exception":{}}" at StreamHandler.php line 156', 'critical')
     (/var/www/davis/vendor/symfony/http-kernel/EventListener/ErrorListener.php:72)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->logKernelException(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (/var/www/davis/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (/var/www/davis/vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))
     (/var/www/davis/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/var/www/davis/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:122)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/var/www/davis/vendor/symfony/http-kernel/HttpKernel.php:241)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(UnexpectedValueException), object(Request), 1)
     (/var/www/davis/vendor/symfony/http-kernel/HttpKernel.php:134)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException(object(UnexpectedValueException), object(Request))
     (/var/www/davis/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:84)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}(object(UnexpectedValueException))
     (/var/www/davis/vendor/symfony/error-handler/ErrorHandler.php:538)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException(object(UnexpectedValueException))                
```

<details>
<summary>
compose.yml and .env (its the same in the example but you can click to open the drop down)
</summary>

```
version: "3.7"
name: "davis-docker"

services:

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - davis
    volumes:
      - davis_www:/var/www/davis
      - type: bind
        source: ./configurations/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 9000:80

  mysql:
    image: mariadb:10.11
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - database:/var/lib/mysql

  davis:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        fpm_user: 101:101
    image: davis:latest
    # If you want to use a prebuilt image from Github
    # image: ghcr.io/tchapi/davis:edge
    container_name: davis
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=mysql
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}?serverVersion=mariadb-10.6.10&charset=utf8mb4
      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_REALM=${AUTH_REALM}
      - AUTH_METHOD=${AUTH_METHOD}
      - CALDAV_ENABLED=${CALDAV_ENABLED}
      - CARDDAV_ENABLED=${CARDDAV_ENABLED}
      - WEBDAV_ENABLED=${WEBDAV_ENABLED}
      - WEBDAV_TMP_DIR=${WEBDAV_TMP_DIR}
      - WEBDAV_PUBLIC_DIR=${WEBDAV_PUBLIC_DIR}
      - WEBDAV_HOMES_DIR=${WEBDAV_HOMES_DIR}
      - INVITE_FROM_ADDRESS=${INVITE_FROM_ADDRESS}
      - APP_TIMEZONE=${TIMEZONE}
    depends_on:
      - mysql
    volumes:
      - davis_www:/var/www/davis

volumes:
  davis_www:
    name: davis_www
  database:
    name: database
```

```
# For the MariaDB container mainly
DB_ROOT_PASSWORD=notSoSecure

TIMEZONE=Europe/Paris

# The Davis database, user and password
DB_DATABASE=davis
DB_USER=davis_user
DB_PASSWORD=davis_password

# For the Davis app
ADMIN_LOGIN=admin
ADMIN_PASSWORD=admin

AUTH_REALM=SabreDAV
AUTH_METHOD=Basic

CALDAV_ENABLED=true
CARDDAV_ENABLED=true
WEBDAV_ENABLED=false

WEBDAV_TMP_DIR='/tmp'
WEBDAV_PUBLIC_DIR='/webdav'
WEBDAV_HOMES_DIR=

INVITE_FROM_ADDRESS=no-reply@example.org
MAIL_HOST=smtp.myprovider.com
MAIL_PORT=587
MAIL_USERNAME=userdav
MAIL_PASSWORD=test
```

</details>

I actually tried the standalone version first (typed in while checking your docker compose examples), there it looped in login screen and wont login. Then I deleted everything and did the all the steps I typed above.
