### ISSUE TITLE
Unable to login with LLDAP and Traefik config

### ISSUE THREAD

**Issue by Daniel-Leer** [tchapi/davis#201]
So I've been banging my head for two days straight. I was able to get the basic docker-standalone setup rolling. Meaning I was able to login with a manually created user via DAVx5. However, I cannot connect via LLDAP, this might be a duplicate to https://github.com/tchapi/davis/issues/158 but I'm also unable to login and followed basically the same config (ldap wise) and debugging steps.

The dev.log does not show any errors, so it seems.

Here is my docker-compose:

```yml

services:
  davis:
    build:
      context: git-repo/
      dockerfile: ./docker/Dockerfile-standalone
      args:
        - fpm_user=82:82 # user and group ID for www-data
        - platform=arm64
    image: local-davis-standalone:5.1.0
    # image: ghcr.io/tchapi/davis:5.1.0
    container_name: davis
    hostname: davis
    depends_on:
      - davis-mariadb
    expose:
      - 9000
    networks:
      - secure_proxy
      - davis_internal
    env_file:
      - ./.env_local
    environment:
      - APP_ENV=dev
      - DATABASE_DRIVER=mysql
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@davis-mariadb:3306/${DB_DATABASE}?serverVersion=mariadb-${MARIA_DB_VERSION}&charset=utf8mb4

      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - INVITE_FROM_ADDRESS=${MAIL_USERNAME}
      - APP_TIMEZONE=${TIMEZONE}

      - ADMIN_AUTH_BYPASS=false
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_REALM=SabreDAV
      - AUTH_METHOD=LDAP

      - CALDAV_ENABLED=true
      - CARDDAV_ENABLED=true

      - WEBDAV_ENABLED=false
      - WEBDAV_TMP_DIR=/tmp
      - WEBDAV_PUBLIC_DIR=/webdav/public
      # By default, home directories are disabled
      - WEBDAV_HOMES_DIR=

      - LDAP_AUTH_URL=ldap://${LDAP_URL}
      - LDAP_DN_PATTERN="uid=%u,ou=people,dc=domain,dc=com"
      - LDAP_MAIL_ATTRIBUTE="mail"
      - LDAP_AUTH_USER_AUTOCREATE=true # false by default
      -  LDAP_CERTIFICATE_CHECKING_STRATEGY="try" # try by default.      
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=secure_proxy' # explictly tell trafik in which network to find this container
      - 'traefik.http.routers.davis.rule=Host( `davis.${LOCAL_DOMAIN_NAME}`, `davis-${EXTERN_HOMELAB_DOMAIN_NAME}` )'
      - 'traefik.http.routers.davis.tls=true'
      - 'traefik.http.routers.davis.entrypoints=websecure'
      - 'traefik.http.routers.davis.middlewares=secured-chain'
      - 'traefik.http.services.davis.loadbalancer.server.port=9000'
      - 'traefik.http.routers.davis.service=davis'


  davis-mariadb:
    image: mariadb:${MARIA_DB_VERSION}
    container_name: davis-mariadb
    hostname: davis-mariadb
    restart: always
    networks:
      - davis_internal
    env_file:
      - ./.env_local
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./davis_data:/var/lib/mysql
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "root", "--password=${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  secure_proxy:
    name: secure_proxy
    external: true
  davis_internal:
    name: davis_internal

```
